---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'swarm_main'
    static_configs:
      # Swarm main process with Discord metrics (Docker service name)
      - targets: ['swarm:9200']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'swarm_manager'
    static_configs:
      # Job manager with orchestration metrics
      - targets: ['manager:9150']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'swarm_worker'
    static_configs:
      # Worker process with system metrics and deployment context
      - targets: ['worker:9100']
    scrape_interval: 15s
    metrics_path: /metrics
