import builtins
from typing import Any, Generic, Literal, Mapping, TypeVar, overload

_T = TypeVar("_T")

class _Pipeline(Generic[_T]):
    def hset(
        self,
        name: str,
        key: str | None = None,
        value: str | None = None,
        *,
        mapping: Mapping[str, str] | None = None,
    ) -> _Pipeline[_T]: ...
    def expire(self, name: str, time: int) -> _Pipeline[_T]: ...
    def delete(self, *names: str) -> _Pipeline[_T]: ...
    def execute(self) -> Any: ...
    def __enter__(self) -> _Pipeline[_T]: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

class Redis(Generic[_T]):
    # Connection
    def ping(self) -> bool: ...
    def info(self, section: str | None = None) -> Any: ...
    def close(self) -> None: ...
    def flushdb(self) -> None: ...
    # Key ops
    def keys(self, pattern: str) -> list[_T] | list[str]: ...
    def exists(self, name: str) -> int: ...
    def delete(self, *names: str) -> int: ...
    def expire(self, name: str, time: int) -> bool | int: ...
    def ttl(self, name: str) -> int: ...

    # String ops
    def set(self, name: str, value: _T) -> bool: ...
    def get(self, name: str) -> _T | None: ...

    # Hash ops
    def hgetall(self, name: str | _T) -> dict[_T, _T] | dict[str, str]: ...
    def hset(
        self,
        name: str,
        key: str | None = None,
        value: str | None = None,
        *,
        mapping: Mapping[str, str] | None = None,
    ) -> int: ...
    def hget(self, name: str, key: str) -> _T | None: ...

    # Set ops
    def sadd(self, name: str, *values: str) -> int: ...
    def smembers(self, name: str) -> builtins.set[str] | builtins.set[_T]: ...
    def srem(self, name: str, *values: str) -> int: ...
    def scard(self, name: str) -> int: ...

    # Pipeline
    def pipeline(self) -> _Pipeline[_T]: ...

@overload
def from_url(
    url: str, *, decode_responses: Literal[False] = ..., **kwargs: Any
) -> Redis[bytes]: ...
@overload
def from_url(url: str, *, decode_responses: Literal[True] = ..., **kwargs: Any) -> Redis[str]: ...

__all__ = ["Redis", "from_url"]
